# Setup
title: Tech-blog
tagline: pythonist
url: 
paginate: 1
baseurl: "tech-blog"
permalink: :title/

kramdown:
    footnote_backlink: "&#10548;"

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - github-pages

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Milko-R
  url: https://milko.pe
  email: milko.cra@gmail.com

# Custom vars
version: 1.0.0
github:
  repo: https://github.com/essentialenemy/noir
